version: '3'

services:
  olu-springboot-container:
    image: olu-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/olu-springboot-container
    ports:
      - "8080-8100:8080"
